server {
    listen 18444 ssl;
    server_name _;

    ssl_certificate /etc/letsencrypt/live/api.phantomhubs.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.phantomhubs.shop/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;

    allow 178.104.184.223;
    allow 127.0.0.1;
    deny all;

    location / {
        proxy_pass https://my.litegames.ir:8000;
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_ssl_name my.litegames.ir;
        proxy_set_header Host my.litegames.ir:8000;
        proxy_set_header Connection "";
        proxy_connect_timeout 10s;
        proxy_read_timeout 75s;
        proxy_send_timeout 30s;
    }
}
